/** Libellés affichés : relatifs + dates calendaires (données fictives) */
export const WHEN_DATE_OPTIONS = [
  "Aujourd’hui",
  "Demain",
  "Après-demain",
  "sam. 22 mars",
  "dim. 23 mars",
  "lun. 24 mars",
  "mar. 25 mars",
  "mer. 26 mars",
  "jeu. 27 mars",
  "ven. 28 mars",
] as const;

export type WhenDateLabel = (typeof WHEN_DATE_OPTIONS)[number];

export type Trip = {
  id: string;
  from: string;
  to: string;
  whenLabel: WhenDateLabel;
  departTime: string; // "HH:MM"
  durationLabel: string;
  seatsLeft: number;
  /** Prix par place en francs guinéens (GNF) */
  priceGNF: number;
  driverName: string;
  carLabel: string;
  distanceLabel: string;
  tags: string[];
};

/** Trajets fictifs entre villes de Guinée */
export const FAKE_TRIPS: Trip[] = [
  {
    id: "t1",
    from: "Conakry",
    to: "Kindia",
    whenLabel: "Aujourd’hui",
    departTime: "07:00",
    durationLabel: "2h 30",
    seatsLeft: 3,
    priceGNF: 45_000,
    driverName: "Amadou Diallo",
    carLabel: "Toyota Corolla",
    distanceLabel: "135 km",
    tags: ["Climatisation", "Bagages ok"],
  },
  {
    id: "t2",
    from: "Conakry",
    to: "Kindia",
    whenLabel: "Demain",
    departTime: "14:30",
    durationLabel: "2h 45",
    seatsLeft: 2,
    priceGNF: 40_000,
    driverName: "Fatoumata Barry",
    carLabel: "Peugeot 308",
    distanceLabel: "135 km",
    tags: ["Départ Kaloum", "Musique"],
  },
  {
    id: "t3",
    from: "Conakry",
    to: "Labé",
    whenLabel: "Après-demain",
    departTime: "05:30",
    durationLabel: "8h 30",
    seatsLeft: 4,
    priceGNF: 180_000,
    driverName: "Ibrahima Camara",
    carLabel: "Toyota Hilux",
    distanceLabel: "450 km",
    tags: ["Grand coffre", "Pauses"],
  },
  {
    id: "t4",
    from: "Conakry",
    to: "Labé",
    whenLabel: "sam. 22 mars",
    departTime: "06:00",
    durationLabel: "8h 15",
    seatsLeft: 1,
    priceGNF: 200_000,
    driverName: "Mamadou Bah",
    carLabel: "Mercedes Sprinter",
    distanceLabel: "450 km",
    tags: ["Sièges confort", "Eau offerte"],
  },
  {
    id: "t5",
    from: "Kindia",
    to: "Mamou",
    whenLabel: "dim. 23 mars",
    departTime: "09:15",
    durationLabel: "2h 00",
    seatsLeft: 3,
    priceGNF: 35_000,
    driverName: "Ousmane Keita",
    carLabel: "Renault Logan",
    distanceLabel: "95 km",
    tags: ["Trajet direct", "Bagages ok"],
  },
  {
    id: "t6",
    from: "Mamou",
    to: "Labé",
    whenLabel: "lun. 24 mars",
    departTime: "11:00",
    durationLabel: "3h 20",
    seatsLeft: 2,
    priceGNF: 55_000,
    driverName: "Aissatou Sow",
    carLabel: "Citroën C3",
    distanceLabel: "180 km",
    tags: ["Route montagne", "Calme"],
  },
  {
    id: "t7",
    from: "Conakry",
    to: "Boké",
    whenLabel: "mar. 25 mars",
    departTime: "08:00",
    durationLabel: "5h 00",
    seatsLeft: 4,
    priceGNF: 120_000,
    driverName: "Thierno Diop",
    carLabel: "Toyota Avensis",
    distanceLabel: "300 km",
    tags: ["Climatisation", "Arrêt Dubréka"],
  },
  {
    id: "t8",
    from: "Boké",
    to: "Conakry",
    whenLabel: "mer. 26 mars",
    departTime: "16:00",
    durationLabel: "4h 45",
    seatsLeft: 3,
    priceGNF: 115_000,
    driverName: "Mariama Touré",
    carLabel: "Hyundai Accent",
    distanceLabel: "300 km",
    tags: ["Retour soir", "Bagages ok"],
  },
  {
    id: "t9",
    from: "Conakry",
    to: "Kankan",
    whenLabel: "jeu. 27 mars",
    departTime: "04:00",
    durationLabel: "11h 00",
    seatsLeft: 3,
    priceGNF: 250_000,
    driverName: "Lamine Condé",
    carLabel: "Toyota Coaster",
    distanceLabel: "620 km",
    tags: ["Long trajet", "Repas pause"],
  },
  {
    id: "t10",
    from: "Kankan",
    to: "Siguiri",
    whenLabel: "ven. 28 mars",
    departTime: "10:30",
    durationLabel: "3h 45",
    seatsLeft: 2,
    priceGNF: 60_000,
    driverName: "Elhadj Sylla",
    carLabel: "Peugeot 301",
    distanceLabel: "165 km",
    tags: ["Mines", "Départ gare"],
  },
  {
    id: "t11",
    from: "Kankan",
    to: "Nzérékoré",
    whenLabel: "Aujourd’hui",
    departTime: "06:30",
    durationLabel: "7h 30",
    seatsLeft: 4,
    priceGNF: 150_000,
    driverName: "Mohamed Kanté",
    carLabel: "Mitsubishi Pajero",
    distanceLabel: "380 km",
    tags: ["4x4", "Forêt"],
  },
  {
    id: "t12",
    from: "Nzérékoré",
    to: "Guéckédou",
    whenLabel: "Demain",
    departTime: "08:45",
    durationLabel: "2h 15",
    seatsLeft: 3,
    priceGNF: 42_000,
    driverName: "Jean-Paul Koulibaly",
    carLabel: "Toyota RAV4",
    distanceLabel: "110 km",
    tags: ["Frontière proche", "Rapide"],
  },
  {
    id: "t13",
    from: "Nzérékoré",
    to: "Macenta",
    whenLabel: "Après-demain",
    departTime: "13:00",
    durationLabel: "1h 30",
    seatsLeft: 1,
    priceGNF: 28_000,
    driverName: "Salimatou Diallo",
    carLabel: "Suzuki Swift",
    distanceLabel: "75 km",
    tags: ["Court trajet", "Précis"],
  },
  {
    id: "t14",
    from: "Conakry",
    to: "Coyah",
    whenLabel: "sam. 22 mars",
    departTime: "17:20",
    durationLabel: "1h 00",
    seatsLeft: 3,
    priceGNF: 25_000,
    driverName: "Abdoulaye Bangoura",
    carLabel: "Dacia Sandero",
    distanceLabel: "50 km",
    tags: ["Banlieue", "Fréquent"],
  },
  {
    id: "t15",
    from: "Coyah",
    to: "Conakry",
    whenLabel: "dim. 23 mars",
    departTime: "06:45",
    durationLabel: "55 min",
    seatsLeft: 2,
    priceGNF: 22_000,
    driverName: "Kadiatou Baldé",
    carLabel: "Toyota Yaris",
    distanceLabel: "50 km",
    tags: ["Matin", "Kaloum"],
  },
  {
    id: "t16",
    from: "Conakry",
    to: "Dubréka",
    whenLabel: "lun. 24 mars",
    departTime: "09:00",
    durationLabel: "45 min",
    seatsLeft: 4,
    priceGNF: 18_000,
    driverName: "Sékou Traoré",
    carLabel: "Peugeot 206",
    distanceLabel: "42 km",
    tags: ["Économique", "Quotidien"],
  },
  {
    id: "t17",
    from: "Labé",
    to: "Pita",
    whenLabel: "mar. 25 mars",
    departTime: "07:30",
    durationLabel: "2h 10",
    seatsLeft: 3,
    priceGNF: 38_000,
    driverName: "Oumar Diallo",
    carLabel: "Renault Kangoo",
    distanceLabel: "120 km",
    tags: ["Foulah", "Montagne"],
  },
  {
    id: "t18",
    from: "Pita",
    to: "Mamou",
    whenLabel: "mer. 26 mars",
    departTime: "12:00",
    durationLabel: "1h 45",
    seatsLeft: 2,
    priceGNF: 32_000,
    driverName: "Hadja Barry",
    carLabel: "Toyota Corolla",
    distanceLabel: "85 km",
    tags: ["Midi", "Confort"],
  },
  {
    id: "t19",
    from: "Kindia",
    to: "Conakry",
    whenLabel: "jeu. 27 mars",
    departTime: "18:00",
    durationLabel: "2h 20",
    seatsLeft: 3,
    priceGNF: 42_000,
    driverName: "Lansana Camara",
    carLabel: "Hyundai i20",
    distanceLabel: "135 km",
    tags: ["Retour soir", "Clim"],
  },
  {
    id: "t20",
    from: "Faranah",
    to: "Kissidougou",
    whenLabel: "ven. 28 mars",
    departTime: "05:45",
    durationLabel: "4h 30",
    seatsLeft: 3,
    priceGNF: 95_000,
    driverName: "Boubacar Diakité",
    carLabel: "Toyota Land Cruiser",
    distanceLabel: "220 km",
    tags: ["Piste", "Expérience"],
  },
  {
    id: "t21",
    from: "Kissidougou",
    to: "Guéckédou",
    whenLabel: "Aujourd’hui",
    departTime: "15:30",
    durationLabel: "1h 15",
    seatsLeft: 4,
    priceGNF: 22_000,
    driverName: "Mariama Diallo",
    carLabel: "Nissan Micra",
    distanceLabel: "55 km",
    tags: ["Court", "Flexible"],
  },
  {
    id: "t22",
    from: "Télimélé",
    to: "Kindia",
    whenLabel: "Demain",
    departTime: "08:30",
    durationLabel: "2h 00",
    seatsLeft: 2,
    priceGNF: 40_000,
    driverName: "Fodé Camara",
    carLabel: "Peugeot Partner",
    distanceLabel: "95 km",
    tags: ["Agriculteurs", "Bagages"],
  },
  {
    id: "t23",
    from: "Fria",
    to: "Conakry",
    whenLabel: "Après-demain",
    departTime: "10:00",
    durationLabel: "3h 30",
    seatsLeft: 3,
    priceGNF: 85_000,
    driverName: "Saïdou Barry",
    carLabel: "Toyota Hiace",
    distanceLabel: "145 km",
    tags: ["Bauxite", "Grand van"],
  },
  {
    id: "t24",
    from: "Conakry",
    to: "Siguiri",
    whenLabel: "sam. 22 mars",
    departTime: "03:30",
    durationLabel: "10h 00",
    seatsLeft: 2,
    priceGNF: 220_000,
    driverName: "Grand Lamine",
    carLabel: "Mercedes 207",
    distanceLabel: "550 km",
    tags: ["Nuit", "Expérience route"],
  },
  {
    id: "t25",
    from: "Conakry",
    to: "Kindia",
    whenLabel: "dim. 23 mars",
    departTime: "07:35",
    durationLabel: "2h 45",
    seatsLeft: 1,
    priceGNF: 50000,
    driverName: "Amadou Diallo",
    carLabel: "Renault Kangoo",
    distanceLabel: "135 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t26",
    from: "Conakry",
    to: "Kindia",
    whenLabel: "lun. 24 mars",
    departTime: "11:53",
    durationLabel: "2h 20",
    seatsLeft: 3,
    priceGNF: 50000,
    driverName: "Ibrahima Camara",
    carLabel: "Toyota Hilux",
    distanceLabel: "135 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t27",
    from: "Conakry",
    to: "Kindia",
    whenLabel: "mar. 25 mars",
    departTime: "15:11",
    durationLabel: "2h 35",
    seatsLeft: 5,
    priceGNF: 50000,
    driverName: "Ousmane Keita",
    carLabel: "Toyota Avensis",
    distanceLabel: "135 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t28",
    from: "Conakry",
    to: "Labé",
    whenLabel: "mer. 26 mars",
    departTime: "10:08",
    durationLabel: "8h 15",
    seatsLeft: 4,
    priceGNF: 150000,
    driverName: "Mariama Touré",
    carLabel: "Toyota Hilux",
    distanceLabel: "450 km",
    tags: ["Grand coffre", "Famille"],
  },
  {
    id: "t29",
    from: "Conakry",
    to: "Labé",
    whenLabel: "jeu. 27 mars",
    departTime: "14:26",
    durationLabel: "7h 45",
    seatsLeft: 1,
    priceGNF: 150000,
    driverName: "Aissatou Sow",
    carLabel: "Toyota Avensis",
    distanceLabel: "450 km",
    tags: ["Arrêt possible", "Flexible"],
  },
  {
    id: "t30",
    from: "Conakry",
    to: "Labé",
    whenLabel: "ven. 28 mars",
    departTime: "18:44",
    durationLabel: "8h 00",
    seatsLeft: 3,
    priceGNF: 150000,
    driverName: "Kadiatou Baldé",
    carLabel: "Renault Logan",
    distanceLabel: "450 km",
    tags: ["Climatisation", "Bagages ok"],
  },
  {
    id: "t31",
    from: "Kindia",
    to: "Mamou",
    whenLabel: "Aujourd’hui",
    departTime: "13:41",
    durationLabel: "2h 00",
    seatsLeft: 2,
    priceGNF: 35000,
    driverName: "Mamadou Bah",
    carLabel: "Toyota Avensis",
    distanceLabel: "95 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t32",
    from: "Kindia",
    to: "Mamou",
    whenLabel: "Demain",
    departTime: "17:59",
    durationLabel: "1h 50",
    seatsLeft: 4,
    priceGNF: 35000,
    driverName: "Sékou Traoré",
    carLabel: "Renault Logan",
    distanceLabel: "95 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t33",
    from: "Kindia",
    to: "Mamou",
    whenLabel: "Après-demain",
    departTime: "07:17",
    durationLabel: "2h 10",
    seatsLeft: 1,
    priceGNF: 35000,
    driverName: "Thierno Diop",
    carLabel: "Dacia Sandero",
    distanceLabel: "95 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t34",
    from: "Kindia",
    to: "Mamou",
    whenLabel: "sam. 22 mars",
    departTime: "11:35",
    durationLabel: "1h 55",
    seatsLeft: 3,
    priceGNF: 35000,
    driverName: "Mohamed Kanté",
    carLabel: "Peugeot Partner",
    distanceLabel: "95 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t35",
    from: "Mamou",
    to: "Labé",
    whenLabel: "dim. 23 mars",
    departTime: "17:25",
    durationLabel: "3h 20",
    seatsLeft: 1,
    priceGNF: 65000,
    driverName: "Thierno Diop",
    carLabel: "Citroën C3",
    distanceLabel: "180 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t36",
    from: "Mamou",
    to: "Labé",
    whenLabel: "lun. 24 mars",
    departTime: "07:43",
    durationLabel: "3h 00",
    seatsLeft: 3,
    priceGNF: 65000,
    driverName: "Mohamed Kanté",
    carLabel: "Nissan Micra",
    distanceLabel: "180 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t37",
    from: "Mamou",
    to: "Labé",
    whenLabel: "mar. 25 mars",
    departTime: "11:01",
    durationLabel: "3h 40",
    seatsLeft: 5,
    priceGNF: 65000,
    driverName: "Boubacar Diakité",
    carLabel: "Renault Kangoo",
    distanceLabel: "180 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t38",
    from: "Mamou",
    to: "Labé",
    whenLabel: "mer. 26 mars",
    departTime: "15:19",
    durationLabel: "3h 10",
    seatsLeft: 2,
    priceGNF: 65000,
    driverName: "Saïdou Barry",
    carLabel: "Toyota Hilux",
    distanceLabel: "180 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t39",
    from: "Conakry",
    to: "Boké",
    whenLabel: "jeu. 27 mars",
    departTime: "07:09",
    durationLabel: "5h 00",
    seatsLeft: 5,
    priceGNF: 110000,
    driverName: "Boubacar Diakité",
    carLabel: "Suzuki Swift",
    distanceLabel: "300 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t40",
    from: "Conakry",
    to: "Boké",
    whenLabel: "ven. 28 mars",
    departTime: "11:27",
    durationLabel: "4h 45",
    seatsLeft: 2,
    priceGNF: 110000,
    driverName: "Saïdou Barry",
    carLabel: "Toyota Yaris",
    distanceLabel: "300 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t41",
    from: "Conakry",
    to: "Boké",
    whenLabel: "Aujourd’hui",
    departTime: "15:45",
    durationLabel: "5h 15",
    seatsLeft: 4,
    priceGNF: 110000,
    driverName: "Hadja Barry",
    carLabel: "Mitsubishi Pajero",
    distanceLabel: "300 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t42",
    from: "Conakry",
    to: "Boké",
    whenLabel: "Demain",
    departTime: "05:03",
    durationLabel: "4h 55",
    seatsLeft: 1,
    priceGNF: 110000,
    driverName: "Grand Lamine",
    carLabel: "Toyota Corolla",
    distanceLabel: "300 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t43",
    from: "Boké",
    to: "Conakry",
    whenLabel: "Après-demain",
    departTime: "11:53",
    durationLabel: "4h 45",
    seatsLeft: 4,
    priceGNF: 110000,
    driverName: "Hadja Barry",
    carLabel: "Mercedes 207",
    distanceLabel: "300 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t44",
    from: "Boké",
    to: "Conakry",
    whenLabel: "sam. 22 mars",
    departTime: "15:11",
    durationLabel: "5h 10",
    seatsLeft: 1,
    priceGNF: 110000,
    driverName: "Grand Lamine",
    carLabel: "Toyota Hiace",
    distanceLabel: "300 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t45",
    from: "Boké",
    to: "Conakry",
    whenLabel: "dim. 23 mars",
    departTime: "05:29",
    durationLabel: "4h 30",
    seatsLeft: 3,
    priceGNF: 110000,
    driverName: "Djibril Diallo",
    carLabel: "Peugeot 308",
    distanceLabel: "300 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t46",
    from: "Boké",
    to: "Conakry",
    whenLabel: "lun. 24 mars",
    departTime: "09:47",
    durationLabel: "5h 00",
    seatsLeft: 5,
    priceGNF: 110000,
    driverName: "Youssouf Keita",
    carLabel: "Hyundai i20",
    distanceLabel: "300 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t47",
    from: "Conakry",
    to: "Kankan",
    whenLabel: "mar. 25 mars",
    departTime: "15:37",
    durationLabel: "11h 00",
    seatsLeft: 3,
    priceGNF: 225000,
    driverName: "Djibril Diallo",
    carLabel: "Toyota Avensis",
    distanceLabel: "620 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t48",
    from: "Conakry",
    to: "Kankan",
    whenLabel: "mer. 26 mars",
    departTime: "05:55",
    durationLabel: "10h 30",
    seatsLeft: 5,
    priceGNF: 225000,
    driverName: "Youssouf Keita",
    carLabel: "Renault Logan",
    distanceLabel: "620 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t49",
    from: "Conakry",
    to: "Kankan",
    whenLabel: "jeu. 27 mars",
    departTime: "09:13",
    durationLabel: "11h 15",
    seatsLeft: 2,
    priceGNF: 225000,
    driverName: "Fatoumata Barry",
    carLabel: "Dacia Sandero",
    distanceLabel: "620 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t50",
    from: "Conakry",
    to: "Kankan",
    whenLabel: "ven. 28 mars",
    departTime: "13:31",
    durationLabel: "10h 45",
    seatsLeft: 4,
    priceGNF: 225000,
    driverName: "Mariama Touré",
    carLabel: "Peugeot Partner",
    distanceLabel: "620 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t51",
    from: "Kankan",
    to: "Siguiri",
    whenLabel: "Aujourd’hui",
    departTime: "05:21",
    durationLabel: "3h 45",
    seatsLeft: 2,
    priceGNF: 60000,
    driverName: "Fatoumata Barry",
    carLabel: "Citroën C3",
    distanceLabel: "165 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t52",
    from: "Kankan",
    to: "Siguiri",
    whenLabel: "Demain",
    departTime: "09:39",
    durationLabel: "3h 30",
    seatsLeft: 4,
    priceGNF: 60000,
    driverName: "Mariama Touré",
    carLabel: "Nissan Micra",
    distanceLabel: "165 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t53",
    from: "Kankan",
    to: "Siguiri",
    whenLabel: "Après-demain",
    departTime: "13:57",
    durationLabel: "4h 00",
    seatsLeft: 1,
    priceGNF: 60000,
    driverName: "Aissatou Sow",
    carLabel: "Renault Kangoo",
    distanceLabel: "165 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t54",
    from: "Kankan",
    to: "Siguiri",
    whenLabel: "sam. 22 mars",
    departTime: "17:15",
    durationLabel: "3h 20",
    seatsLeft: 3,
    priceGNF: 60000,
    driverName: "Kadiatou Baldé",
    carLabel: "Toyota Hilux",
    distanceLabel: "165 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t55",
    from: "Kankan",
    to: "Nzérékoré",
    whenLabel: "dim. 23 mars",
    departTime: "09:05",
    durationLabel: "7h 30",
    seatsLeft: 1,
    priceGNF: 135000,
    driverName: "Aissatou Sow",
    carLabel: "Suzuki Swift",
    distanceLabel: "380 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t56",
    from: "Kankan",
    to: "Nzérékoré",
    whenLabel: "lun. 24 mars",
    departTime: "13:23",
    durationLabel: "7h 00",
    seatsLeft: 3,
    priceGNF: 135000,
    driverName: "Kadiatou Baldé",
    carLabel: "Toyota Yaris",
    distanceLabel: "380 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t57",
    from: "Kankan",
    to: "Nzérékoré",
    whenLabel: "mar. 25 mars",
    departTime: "17:41",
    durationLabel: "8h 00",
    seatsLeft: 5,
    priceGNF: 135000,
    driverName: "Lansana Camara",
    carLabel: "Mitsubishi Pajero",
    distanceLabel: "380 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t58",
    from: "Kankan",
    to: "Nzérékoré",
    whenLabel: "mer. 26 mars",
    departTime: "07:59",
    durationLabel: "7h 15",
    seatsLeft: 2,
    priceGNF: 135000,
    driverName: "Elhadj Sylla",
    carLabel: "Toyota Corolla",
    distanceLabel: "380 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t59",
    from: "Nzérékoré",
    to: "Guéckédou",
    whenLabel: "jeu. 27 mars",
    departTime: "13:49",
    durationLabel: "2h 15",
    seatsLeft: 5,
    priceGNF: 40000,
    driverName: "Lansana Camara",
    carLabel: "Mercedes 207",
    distanceLabel: "110 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t60",
    from: "Nzérékoré",
    to: "Guéckédou",
    whenLabel: "ven. 28 mars",
    departTime: "17:07",
    durationLabel: "2h 00",
    seatsLeft: 2,
    priceGNF: 40000,
    driverName: "Elhadj Sylla",
    carLabel: "Toyota Hiace",
    distanceLabel: "110 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t61",
    from: "Nzérékoré",
    to: "Guéckédou",
    whenLabel: "Aujourd’hui",
    departTime: "07:25",
    durationLabel: "2h 30",
    seatsLeft: 4,
    priceGNF: 40000,
    driverName: "Salimatou Diallo",
    carLabel: "Peugeot 308",
    distanceLabel: "110 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t62",
    from: "Nzérékoré",
    to: "Guéckédou",
    whenLabel: "Demain",
    departTime: "11:43",
    durationLabel: "1h 55",
    seatsLeft: 1,
    priceGNF: 40000,
    driverName: "Fodé Camara",
    carLabel: "Hyundai i20",
    distanceLabel: "110 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t63",
    from: "Nzérékoré",
    to: "Macenta",
    whenLabel: "Après-demain",
    departTime: "17:33",
    durationLabel: "1h 30",
    seatsLeft: 4,
    priceGNF: 25000,
    driverName: "Salimatou Diallo",
    carLabel: "Toyota Avensis",
    distanceLabel: "75 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t64",
    from: "Nzérékoré",
    to: "Macenta",
    whenLabel: "sam. 22 mars",
    departTime: "07:51",
    durationLabel: "1h 15",
    seatsLeft: 1,
    priceGNF: 25000,
    driverName: "Fodé Camara",
    carLabel: "Renault Logan",
    distanceLabel: "75 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t65",
    from: "Nzérékoré",
    to: "Macenta",
    whenLabel: "dim. 23 mars",
    departTime: "11:09",
    durationLabel: "1h 45",
    seatsLeft: 3,
    priceGNF: 25000,
    driverName: "Oumar Diallo",
    carLabel: "Dacia Sandero",
    distanceLabel: "75 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t66",
    from: "Nzérékoré",
    to: "Macenta",
    whenLabel: "lun. 24 mars",
    departTime: "15:27",
    durationLabel: "1h 20",
    seatsLeft: 5,
    priceGNF: 25000,
    driverName: "Jean-Paul Koulibaly",
    carLabel: "Peugeot Partner",
    distanceLabel: "75 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t67",
    from: "Conakry",
    to: "Coyah",
    whenLabel: "mar. 25 mars",
    departTime: "07:17",
    durationLabel: "1h 00",
    seatsLeft: 3,
    priceGNF: 20000,
    driverName: "Oumar Diallo",
    carLabel: "Citroën C3",
    distanceLabel: "50 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t68",
    from: "Conakry",
    to: "Coyah",
    whenLabel: "mer. 26 mars",
    departTime: "11:35",
    durationLabel: "55 min",
    seatsLeft: 5,
    priceGNF: 20000,
    driverName: "Jean-Paul Koulibaly",
    carLabel: "Nissan Micra",
    distanceLabel: "50 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t69",
    from: "Conakry",
    to: "Coyah",
    whenLabel: "jeu. 27 mars",
    departTime: "15:53",
    durationLabel: "1h 10",
    seatsLeft: 2,
    priceGNF: 20000,
    driverName: "Abdoulaye Bangoura",
    carLabel: "Renault Kangoo",
    distanceLabel: "50 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t70",
    from: "Conakry",
    to: "Coyah",
    whenLabel: "ven. 28 mars",
    departTime: "05:11",
    durationLabel: "50 min",
    seatsLeft: 4,
    priceGNF: 20000,
    driverName: "Ramatoulaye Bah",
    carLabel: "Toyota Hilux",
    distanceLabel: "50 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t71",
    from: "Coyah",
    to: "Conakry",
    whenLabel: "Aujourd’hui",
    departTime: "11:01",
    durationLabel: "55 min",
    seatsLeft: 2,
    priceGNF: 20000,
    driverName: "Abdoulaye Bangoura",
    carLabel: "Suzuki Swift",
    distanceLabel: "50 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t72",
    from: "Coyah",
    to: "Conakry",
    whenLabel: "Demain",
    departTime: "15:19",
    durationLabel: "1h 05",
    seatsLeft: 4,
    priceGNF: 20000,
    driverName: "Ramatoulaye Bah",
    carLabel: "Toyota Yaris",
    distanceLabel: "50 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t73",
    from: "Coyah",
    to: "Conakry",
    whenLabel: "Après-demain",
    departTime: "05:37",
    durationLabel: "50 min",
    seatsLeft: 1,
    priceGNF: 20000,
    driverName: "Amadou Diallo",
    carLabel: "Mitsubishi Pajero",
    distanceLabel: "50 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t74",
    from: "Coyah",
    to: "Conakry",
    whenLabel: "sam. 22 mars",
    departTime: "09:55",
    durationLabel: "1h 00",
    seatsLeft: 3,
    priceGNF: 20000,
    driverName: "Ibrahima Camara",
    carLabel: "Toyota Corolla",
    distanceLabel: "50 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t75",
    from: "Conakry",
    to: "Dubréka",
    whenLabel: "dim. 23 mars",
    departTime: "15:45",
    durationLabel: "45 min",
    seatsLeft: 1,
    priceGNF: 15000,
    driverName: "Amadou Diallo",
    carLabel: "Mercedes 207",
    distanceLabel: "42 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t76",
    from: "Conakry",
    to: "Dubréka",
    whenLabel: "lun. 24 mars",
    departTime: "05:03",
    durationLabel: "40 min",
    seatsLeft: 3,
    priceGNF: 15000,
    driverName: "Ibrahima Camara",
    carLabel: "Toyota Hiace",
    distanceLabel: "42 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t77",
    from: "Conakry",
    to: "Dubréka",
    whenLabel: "mar. 25 mars",
    departTime: "09:21",
    durationLabel: "50 min",
    seatsLeft: 5,
    priceGNF: 15000,
    driverName: "Ousmane Keita",
    carLabel: "Peugeot 308",
    distanceLabel: "42 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t78",
    from: "Conakry",
    to: "Dubréka",
    whenLabel: "mer. 26 mars",
    departTime: "13:39",
    durationLabel: "42 min",
    seatsLeft: 2,
    priceGNF: 15000,
    driverName: "Mamadou Bah",
    carLabel: "Hyundai i20",
    distanceLabel: "42 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t79",
    from: "Labé",
    to: "Pita",
    whenLabel: "jeu. 27 mars",
    departTime: "05:29",
    durationLabel: "2h 10",
    seatsLeft: 5,
    priceGNF: 45000,
    driverName: "Ousmane Keita",
    carLabel: "Toyota Avensis",
    distanceLabel: "120 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t80",
    from: "Labé",
    to: "Pita",
    whenLabel: "ven. 28 mars",
    departTime: "09:47",
    durationLabel: "2h 00",
    seatsLeft: 2,
    priceGNF: 45000,
    driverName: "Mamadou Bah",
    carLabel: "Renault Logan",
    distanceLabel: "120 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t81",
    from: "Labé",
    to: "Pita",
    whenLabel: "Aujourd’hui",
    departTime: "13:05",
    durationLabel: "2h 20",
    seatsLeft: 4,
    priceGNF: 45000,
    driverName: "Sékou Traoré",
    carLabel: "Dacia Sandero",
    distanceLabel: "120 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t82",
    from: "Labé",
    to: "Pita",
    whenLabel: "Demain",
    departTime: "17:23",
    durationLabel: "1h 55",
    seatsLeft: 1,
    priceGNF: 45000,
    driverName: "Thierno Diop",
    carLabel: "Peugeot Partner",
    distanceLabel: "120 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t83",
    from: "Pita",
    to: "Mamou",
    whenLabel: "Après-demain",
    departTime: "09:13",
    durationLabel: "1h 45",
    seatsLeft: 4,
    priceGNF: 30000,
    driverName: "Sékou Traoré",
    carLabel: "Citroën C3",
    distanceLabel: "85 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t84",
    from: "Pita",
    to: "Mamou",
    whenLabel: "sam. 22 mars",
    departTime: "13:31",
    durationLabel: "1h 30",
    seatsLeft: 1,
    priceGNF: 30000,
    driverName: "Thierno Diop",
    carLabel: "Nissan Micra",
    distanceLabel: "85 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t85",
    from: "Pita",
    to: "Mamou",
    whenLabel: "dim. 23 mars",
    departTime: "17:49",
    durationLabel: "2h 00",
    seatsLeft: 3,
    priceGNF: 30000,
    driverName: "Mohamed Kanté",
    carLabel: "Renault Kangoo",
    distanceLabel: "85 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t86",
    from: "Pita",
    to: "Mamou",
    whenLabel: "lun. 24 mars",
    departTime: "07:07",
    durationLabel: "1h 40",
    seatsLeft: 5,
    priceGNF: 30000,
    driverName: "Boubacar Diakité",
    carLabel: "Toyota Hilux",
    distanceLabel: "85 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t87",
    from: "Kindia",
    to: "Conakry",
    whenLabel: "mar. 25 mars",
    departTime: "13:57",
    durationLabel: "2h 20",
    seatsLeft: 3,
    priceGNF: 50000,
    driverName: "Mohamed Kanté",
    carLabel: "Suzuki Swift",
    distanceLabel: "135 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t88",
    from: "Kindia",
    to: "Conakry",
    whenLabel: "mer. 26 mars",
    departTime: "17:15",
    durationLabel: "2h 35",
    seatsLeft: 5,
    priceGNF: 50000,
    driverName: "Boubacar Diakité",
    carLabel: "Toyota Yaris",
    distanceLabel: "135 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t89",
    from: "Kindia",
    to: "Conakry",
    whenLabel: "jeu. 27 mars",
    departTime: "07:33",
    durationLabel: "2h 10",
    seatsLeft: 2,
    priceGNF: 50000,
    driverName: "Saïdou Barry",
    carLabel: "Mitsubishi Pajero",
    distanceLabel: "135 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t90",
    from: "Kindia",
    to: "Conakry",
    whenLabel: "ven. 28 mars",
    departTime: "11:51",
    durationLabel: "2h 25",
    seatsLeft: 4,
    priceGNF: 50000,
    driverName: "Hadja Barry",
    carLabel: "Toyota Corolla",
    distanceLabel: "135 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t91",
    from: "Faranah",
    to: "Kissidougou",
    whenLabel: "Aujourd’hui",
    departTime: "17:41",
    durationLabel: "4h 30",
    seatsLeft: 2,
    priceGNF: 80000,
    driverName: "Saïdou Barry",
    carLabel: "Mercedes 207",
    distanceLabel: "220 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t92",
    from: "Faranah",
    to: "Kissidougou",
    whenLabel: "Demain",
    departTime: "07:59",
    durationLabel: "4h 15",
    seatsLeft: 4,
    priceGNF: 80000,
    driverName: "Hadja Barry",
    carLabel: "Toyota Hiace",
    distanceLabel: "220 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t93",
    from: "Faranah",
    to: "Kissidougou",
    whenLabel: "Après-demain",
    departTime: "11:17",
    durationLabel: "4h 45",
    seatsLeft: 1,
    priceGNF: 80000,
    driverName: "Grand Lamine",
    carLabel: "Peugeot 308",
    distanceLabel: "220 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t94",
    from: "Faranah",
    to: "Kissidougou",
    whenLabel: "sam. 22 mars",
    departTime: "15:35",
    durationLabel: "4h 00",
    seatsLeft: 3,
    priceGNF: 80000,
    driverName: "Djibril Diallo",
    carLabel: "Hyundai i20",
    distanceLabel: "220 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t95",
    from: "Kissidougou",
    to: "Guéckédou",
    whenLabel: "dim. 23 mars",
    departTime: "07:25",
    durationLabel: "1h 15",
    seatsLeft: 1,
    priceGNF: 20000,
    driverName: "Grand Lamine",
    carLabel: "Toyota Avensis",
    distanceLabel: "55 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t96",
    from: "Kissidougou",
    to: "Guéckédou",
    whenLabel: "lun. 24 mars",
    departTime: "11:43",
    durationLabel: "1h 00",
    seatsLeft: 3,
    priceGNF: 20000,
    driverName: "Djibril Diallo",
    carLabel: "Renault Logan",
    distanceLabel: "55 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t97",
    from: "Kissidougou",
    to: "Guéckédou",
    whenLabel: "mar. 25 mars",
    departTime: "15:01",
    durationLabel: "1h 20",
    seatsLeft: 5,
    priceGNF: 20000,
    driverName: "Youssouf Keita",
    carLabel: "Dacia Sandero",
    distanceLabel: "55 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t98",
    from: "Kissidougou",
    to: "Guéckédou",
    whenLabel: "mer. 26 mars",
    departTime: "05:19",
    durationLabel: "1h 10",
    seatsLeft: 2,
    priceGNF: 20000,
    driverName: "Fatoumata Barry",
    carLabel: "Peugeot Partner",
    distanceLabel: "55 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t99",
    from: "Télimélé",
    to: "Kindia",
    whenLabel: "jeu. 27 mars",
    departTime: "11:09",
    durationLabel: "2h 00",
    seatsLeft: 5,
    priceGNF: 35000,
    driverName: "Youssouf Keita",
    carLabel: "Citroën C3",
    distanceLabel: "95 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t100",
    from: "Télimélé",
    to: "Kindia",
    whenLabel: "ven. 28 mars",
    departTime: "15:27",
    durationLabel: "1h 50",
    seatsLeft: 2,
    priceGNF: 35000,
    driverName: "Fatoumata Barry",
    carLabel: "Nissan Micra",
    distanceLabel: "95 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t101",
    from: "Télimélé",
    to: "Kindia",
    whenLabel: "Aujourd’hui",
    departTime: "05:45",
    durationLabel: "2h 10",
    seatsLeft: 4,
    priceGNF: 35000,
    driverName: "Mariama Touré",
    carLabel: "Renault Kangoo",
    distanceLabel: "95 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t102",
    from: "Télimélé",
    to: "Kindia",
    whenLabel: "Demain",
    departTime: "09:03",
    durationLabel: "1h 45",
    seatsLeft: 1,
    priceGNF: 35000,
    driverName: "Aissatou Sow",
    carLabel: "Toyota Hilux",
    distanceLabel: "95 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t103",
    from: "Fria",
    to: "Conakry",
    whenLabel: "Après-demain",
    departTime: "15:53",
    durationLabel: "3h 30",
    seatsLeft: 4,
    priceGNF: 50000,
    driverName: "Mariama Touré",
    carLabel: "Suzuki Swift",
    distanceLabel: "145 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t104",
    from: "Fria",
    to: "Conakry",
    whenLabel: "sam. 22 mars",
    departTime: "05:11",
    durationLabel: "3h 15",
    seatsLeft: 1,
    priceGNF: 50000,
    driverName: "Aissatou Sow",
    carLabel: "Toyota Yaris",
    distanceLabel: "145 km",
    tags: ["Musique", "Confort"],
  },
  {
    id: "t105",
    from: "Fria",
    to: "Conakry",
    whenLabel: "dim. 23 mars",
    departTime: "09:29",
    durationLabel: "3h 45",
    seatsLeft: 3,
    priceGNF: 50000,
    driverName: "Kadiatou Baldé",
    carLabel: "Mitsubishi Pajero",
    distanceLabel: "145 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t106",
    from: "Fria",
    to: "Conakry",
    whenLabel: "lun. 24 mars",
    departTime: "13:47",
    durationLabel: "3h 00",
    seatsLeft: 5,
    priceGNF: 50000,
    driverName: "Lansana Camara",
    carLabel: "Toyota Corolla",
    distanceLabel: "145 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t107",
    from: "Conakry",
    to: "Siguiri",
    whenLabel: "mar. 25 mars",
    departTime: "05:37",
    durationLabel: "10h 00",
    seatsLeft: 3,
    priceGNF: 200000,
    driverName: "Kadiatou Baldé",
    carLabel: "Mercedes 207",
    distanceLabel: "550 km",
    tags: ["Trajet direct", "Silencieux"],
  },
  {
    id: "t108",
    from: "Conakry",
    to: "Siguiri",
    whenLabel: "mer. 26 mars",
    departTime: "09:55",
    durationLabel: "9h 45",
    seatsLeft: 5,
    priceGNF: 200000,
    driverName: "Lansana Camara",
    carLabel: "Toyota Hiace",
    distanceLabel: "550 km",
    tags: ["Wi‑Fi", "USB"],
  },
  {
    id: "t109",
    from: "Conakry",
    to: "Siguiri",
    whenLabel: "jeu. 27 mars",
    departTime: "13:13",
    durationLabel: "10h 20",
    seatsLeft: 2,
    priceGNF: 200000,
    driverName: "Elhadj Sylla",
    carLabel: "Peugeot 308",
    distanceLabel: "550 km",
    tags: ["Sièges larges", "Propre"],
  },
  {
    id: "t110",
    from: "Conakry",
    to: "Siguiri",
    whenLabel: "ven. 28 mars",
    departTime: "17:31",
    durationLabel: "9h 30",
    seatsLeft: 4,
    priceGNF: 200000,
    driverName: "Salimatou Diallo",
    carLabel: "Hyundai i20",
    distanceLabel: "550 km",
    tags: ["Musique", "Confort"],
  },
];

/** Villes uniques extraites des trajets (pour l'autocomplete) */
export const CITIES = Array.from(
  new Set(FAKE_TRIPS.flatMap((t) => [t.from, t.to])),
).sort();

function normalizeCity(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "");
}

/** Filtre les trajets selon départ, arrivée et places minimum (optionnel). */
export function filterTripsBySearch(
  from: string,
  to: string,
  placesMin: number | null,
): Trip[] {
  const f = normalizeCity(from);
  const t = normalizeCity(to);
  return FAKE_TRIPS.filter((trip) => {
    if (normalizeCity(trip.from) !== f || normalizeCity(trip.to) !== t)
      return false;
    if (placesMin != null && trip.seatsLeft < placesMin) return false;
    return true;
  });
}
